#ifndef DC_SPINNER_CONFIG

#define DC_SPINNER_CONFIG 1

#define DC_SPINNER_SPINNER_RANGE_BOUND_CAP		0
#define DC_SPINNER_SPINNER_RANGE_BOUND_LOOP		1

#define DC_SPINNER_VAR_KEY_INSTANCE				"dcspin_0"
#define DC_SPINNER_VAR_KEY_INCREMENT			"dcspin_1"
#define DC_SPINNER_VAR_KEY_RANGE_BOUND_LOWER	"dcspin_2"
#define DC_SPINNER_VAR_KEY_RANGE_BOUND_UPPER	"dcspin_3"
#define DC_SPINNER_VAR_KEY_RANGE_LOWER			"dcspin_4"
#define DC_SPINNER_VAR_KEY_RANGE_UPPER			"dcspin_5"
#define DC_SPINNER_VAR_KEY_STEPS				"dcspin_6"
#define DC_SPINNER_VAR_KEY_VALUE				"dcspin_7"

#define DC_SPINNER_DEFAULT_INSTANCE					0
#define DC_SPINNER_DEFAULT_RANGE_BOUND_LOWER	DC_SPINNER_SPINNER_RANGE_BOUND_LOOP
#define DC_SPINNER_DEFAULT_RANGE_BOUND_UPPER	DC_SPINNER_SPINNER_RANGE_BOUND_LOOP
#define DC_SPINNER_DEFAULT_VALUE				0
#define DC_SPINNER_DEFAULT_INCREMENT			1
#define DC_SPINNER_DEFAULT_RANGE_LOWER			0 
#define DC_SPINNER_DEFAULT_RANGE_UPPER			100 
#define DC_SPINNER_DEFAULT_STEPS				100
	

#endif // !DC_SPINNER_CONFIG
